"""Validate the Python port against reference outputs generated by R DiffCorr."""
import numpy as np
import pandas as pd
import pytest

import diffcorr as dc
from diffcorr import datasets

# iris, mirrored from R's built-in dataset, used by several R examples.
from iris_data import iris_df  # provided by tests/iris_data.py


# --------------------------------------------------------------------------- #
# scalar / vector stats
# --------------------------------------------------------------------------- #
def test_cor2_test():
    assert dc.cor2_test(30, 0.6) == pytest.approx(0.000457055239405078)


def test_compcorr():
    res = dc.compcorr(10, 0.1, 10, 0.9)
    assert isinstance(res, dict)
    assert res["diff"] == pytest.approx(-2.56656021657955)
    assert res["pval"] == pytest.approx(0.010271278955442)


def test_get_lfdr_matches_fdrtool():
    pv = datasets.load_pvalues().to_numpy()
    res = dc.get_lfdr(pv)
    assert res["lfdr"][0] == pytest.approx(0.649926998163217, rel=1e-6)


def test_get_min_max():
    res = dc.get_min_max(iris_df().iloc[:, :2])
    assert res["max"] == pytest.approx(7.9)
    assert res["min"] == pytest.approx(2.0)
    assert res["max_i"] == 132


# --------------------------------------------------------------------------- #
# scaling
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize("method", ["auto", "range", "pareto", "vast", "level", "power"])
def test_scaling_methods(method, ref):
    out = dc.scaling_methods(iris_df().iloc[:, :4], method)
    expected = ref(f"scaling_{method}.csv")
    np.testing.assert_allclose(out.to_numpy(), expected.to_numpy(), rtol=1e-9, atol=1e-12)


def test_scaling_single_column_returns_none():
    assert dc.scaling_methods(iris_df().iloc[:, :1], "auto") is None


# --------------------------------------------------------------------------- #
# distances
# --------------------------------------------------------------------------- #
def test_cor_dist(ref):
    out = dc.cor_dist(iris_df().iloc[:, :4].T.to_numpy())
    expected = ref("cordist_iris.csv").to_numpy()
    np.testing.assert_allclose(out, expected, rtol=1e-9, atol=1e-12)
    assert out[0, 1] == pytest.approx(1.117569784133)


def test_uncent_cor2dist():
    res = dc.uncent_cor2dist(iris_df().iloc[:, :4].T.to_numpy(), 0)
    assert res[1] == pytest.approx(0.021986797478038, rel=1e-5)


def test_uncent_cordist(ref):
    out = dc.uncent_cordist(iris_df().iloc[:, :4].T.to_numpy())
    expected = ref("uncentcordist_iris.csv").to_numpy()
    # R allocated a non-square matrix; compare the (correct) populated block.
    m = out.shape[0]
    np.testing.assert_allclose(out, expected[:, :m], rtol=1e-9, atol=1e-9)
    assert out[0, 1] == pytest.approx(0.0219867974780388)


# --------------------------------------------------------------------------- #
# differential correlation
# --------------------------------------------------------------------------- #
def _comp_leaves():
    leaves = datasets.load_AraMetLeaves()
    d1 = np.log10(leaves.iloc[:, 0:17])
    d2 = np.log10(leaves.iloc[:, 17:37])
    # threshold > 1 keeps every pair (avoids floating-point ties exactly at 1.0)
    return dc.comp_2_cc_fdr(d1, d2, method="pearson", threshold=1.01)


def test_comp_2_cc_fdr_columns():
    res = _comp_leaves()
    assert isinstance(res, pd.DataFrame)
    expected_cols = ["molecule X", "molecule Y", "r1", "p1", "r2", "p2",
                     "p (difference)", "(r1-r2)", "lfdr (in cond. 1)",
                     "lfdr (in cond. 2)", "lfdr (difference)"]
    assert list(res.columns) == expected_cols


def test_comp_2_cc_fdr_values(ref):
    res = _comp_leaves()
    expected = ref("comp2ccfdr_leaves.csv")
    assert len(res) == len(expected)
    # align by molecule pair, compare numerics
    key = ["molecule X", "molecule Y"]
    merged = res.merge(expected, on=key, suffixes=("_py", "_r"))
    assert len(merged) == len(res)
    for c in ["r1", "p1", "r2", "p2", "p (difference)", "(r1-r2)",
              "lfdr (in cond. 1)", "lfdr (in cond. 2)", "lfdr (difference)"]:
        np.testing.assert_allclose(merged[f"{c}_py"].to_numpy(float),
                                   merged[f"{c}_r"].to_numpy(float),
                                   rtol=1e-6, atol=1e-8, err_msg=c)


def test_comp_2_cc_fdr_malate_threonine():
    res = _comp_leaves()
    row = res[(res["molecule X"] == "Malate") & (res["molecule Y"] == "Threonine")]
    assert not row.empty
    assert row["r1"].iloc[0] == pytest.approx(0.765864054338824)


def test_comp_2_cc_fdr_BH(ref):
    leaves = datasets.load_AraMetLeaves()
    res = dc.comp_2_cc_fdr(np.log10(leaves.iloc[:, 0:17]),
                           np.log10(leaves.iloc[:, 17:37]),
                           method="pearson", p_adjust_methods="BH", threshold=1.01)
    expected = ref("comp2ccfdr_leaves_BH.csv")
    merged = res.merge(expected, on=["molecule X", "molecule Y"], suffixes=("_py", "_r"))
    np.testing.assert_allclose(merged["lfdr (difference)_py"].to_numpy(float),
                               merged["lfdr (difference)_r"].to_numpy(float),
                               rtol=1e-8, atol=1e-10)


# --------------------------------------------------------------------------- #
# clustering
# --------------------------------------------------------------------------- #
def test_cluster_molecule_heights(ref):
    leaves = datasets.load_AraMetLeaves()
    hc1 = dc.cluster_molecule(leaves.iloc[:, 0:17], "pearson", "average")
    expected = ref("hc1_height.csv")["h1"].to_numpy()
    np.testing.assert_allclose(np.sort(hc1.height), np.sort(expected), rtol=1e-9, atol=1e-12)
    assert hc1.method == "average"
    assert len(hc1.labels) == 59


def test_cutree_matches_r(ref):
    golub = datasets.load_golub_df()
    hc = dc.cluster_molecule(golub.iloc[:, 0:27], "pearson", "average")
    g = dc.cutree(hc, h=0.4)
    expected = ref("golubdf_cutree04.csv")
    np.testing.assert_array_equal(g.to_numpy(), expected["group"].to_numpy())


# --------------------------------------------------------------------------- #
# eigen molecules + graphs
# --------------------------------------------------------------------------- #
def test_get_eigen_molecule(ref):
    golub = datasets.load_golub_df()
    hc = dc.cluster_molecule(golub.iloc[:, 0:27], "pearson", "average")
    g1 = dc.cutree(hc, h=0.4)
    res = dc.get_eigen_molecule(golub, g1)
    expected = ref("eigen_golubdf.csv")
    assert sorted(res["group"]) == sorted(expected["group"].tolist())
    by_group = dict(zip(res["group"], res["N"]))
    for _, r in expected.iterrows():
        assert by_group[r["group"]] == r["N"]
    mc = dict(zip(res["group"], res["mean_corr"]))
    for _, r in expected.iterrows():
        assert mc[r["group"]] == pytest.approx(r["mean.corr"], rel=1e-8)


def test_get_eigen_molecule_graph_counts(ref):
    golub = datasets.load_golub_df()
    hc = dc.cluster_molecule(golub.iloc[:, 0:27], "pearson", "average")
    g1 = dc.cutree(hc, h=0.4)
    res = dc.get_eigen_molecule(golub, g1)
    g = dc.get_eigen_molecule_graph(res)
    expected = ref("eigen_graph_counts.csv")
    assert g.number_of_nodes() == int(expected["nV"][0])
    assert g.number_of_edges() == int(expected["nE"][0])


# --------------------------------------------------------------------------- #
# datasets
# --------------------------------------------------------------------------- #
def test_datasets_shapes():
    assert datasets.load_AraMetLeaves().shape == (59, 50)
    assert datasets.load_AraMetRoots().shape == (59, 53)
    assert datasets.load_golub_df().shape == (2568, 38)
    assert datasets.load_pvalues().shape == (4289,)
    assert datasets.load_AraMetLeaves().columns[0] == "Col0.1"
    assert datasets.load_AraMetLeaves().columns[49] == "mto1.13"


# --------------------------------------------------------------------------- #
# plotting smoke tests
# --------------------------------------------------------------------------- #
def test_plot_cluster_molecules_runs():
    import matplotlib
    matplotlib.use("Agg")
    golub = datasets.load_golub_df()
    hc = dc.cluster_molecule(golub.iloc[:, 0:27], "pearson", "average")
    g1 = dc.cutree(hc, h=0.4)
    ax = dc.plot_cluster_molecules(golub.iloc[:, 0:27], g1, 1)
    assert ax is not None


def test_write_modules(tmp_path):
    golub = datasets.load_golub_df()
    hc = dc.cluster_molecule(golub.iloc[:, 0:27], "pearson", "average")
    g1 = dc.cutree(hc, h=0.4)
    res = dc.get_eigen_molecule(golub, g1)
    out = tmp_path / "modules.txt"
    dc.write_modules(g1, res, str(out))
    text = out.read_text().splitlines()
    assert text[0].startswith("Molecule number")
    assert len(text) > 1
